feat(wttrin): aggiunti update forzato e attesa max

diff --git a/BIN/wttrin b/BIN/wttrin
--- a/BIN/wttrin
+++ b/BIN/wttrin
@@ -20,6 +20,7 @@
 # --- Impostazioni Predefinite ---
 DEFAULT_LANG="en"
 DEFAULT_CACHE_MINUTES=30
+DEFAULT_MAX_WAIT=5
 
 # --- Funzioni ---
 
@@ -28,6 +29,7 @@ usage() {
     echo "Uso: $(basename "$0") [-l LINGUA] [-t MINUTI]"
     echo "  -l: Codice lingua (es: it, en, fr). Default: ${DEFAULT_LANG}"
     echo "  -t: Durata della cache in minuti. Default: ${DEFAULT_CACHE_MINUTES}"
+    echo "  -w: Massima attesa consentita. Default: ${DEFAULT_MAX_WAIT}"
     exit 1
 }
 
@@ -42,7 +44,7 @@ check_dependencies() {
 # Recupera le informazioni meteo e le salva nella cache
 fetch_weather() {
     # Il flag -s per curl esegue l'operazione in modalità silenziosa
-    curl -s "http://wttr.in?lang=${LANGUAGE}&0npq" > "${CACHE_FILE}"
+    curl -s -m $MAX_WAIT "http://wttr.in?lang=${LANGUAGE}&0npq" > "${CACHE_FILE}"
 }
 
 # --- Script Principale ---
@@ -53,9 +55,11 @@ check_dependencies
 # Imposta i valori di default
 LANGUAGE="${DEFAULT_LANG}"
 CACHE_MINUTES="${DEFAULT_CACHE_MINUTES}"
+MAX_WAIT="${DEFAULT_MAX_WAIT}"
+FORCE_UPDATE=0
 
 # Analizza le opzioni passate allo script
-while getopts "l:t:h" opt; do
+while getopts "l:t:w:fh" opt; do
     case "${opt}" in
         l)
             LANGUAGE="${OPTARG}"
@@ -71,6 +75,21 @@ while getopts "l:t:h" opt; do
                     CACHE_MINUTES="${OPTARG}"
                     ;;
             esac
+            ;;
+        w)
+            # Validazione di base per assicurarsi che il tempo sia un numero intero
+            case "${OPTARG}" in
+                ''|*[!0-9]*)
+                    echo "Errore: Il tempo deve essere un numero intero positivo." >&2
+                    usage
+                    ;;
+                *)
+                    MAX_WAIT="${OPTARG}"
+                    ;;
+            esac
+            ;;
+        f)
+            FORCE_UPDATE=1
             ;;
         h|*)
             usage
@@ -96,7 +115,7 @@ if [ -s "${CACHE_FILE}" ]; then
 fi
 
 # Se la cache deve essere aggiornata (perché non esiste, è vuota o è scaduta)
-if [ "${UPDATE_CACHE}" -eq 1 ]; then
+if [ "${UPDATE_CACHE}" -eq 1 ] || [ "${FORCE_UPDATE}" -eq 1 ]; then
     fetch_weather
 fi
 
